server:
  port: 9100

spring:
  application:
    name: frontend
  config:
    import: optional:file:.env[.properties]

auth:
  loginLink: ${LOGIN_USER_LINK}
  registerLink: ${REGISTER_USER_LINK}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9101/eureka
