server:
  port: 9099
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
