server:
  port: 9099
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

rest:
  userServiceLink: http://localhost:9097/api/v1/crud/users
