server:
  port: 9099
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/
    username: postgres
    password: postgres

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

rest:
  userServiceLink: http://localhost:9097/api/v1/crud/users
