server:
  port: 9098

secret:
  token: t.VqnElEfrPsAXQfuhO8JgcnOUhpz9dI3dNq6yFntZaSuRtU7eKgBNusIpTIifs14jsPfI5hRl47JXsByKqWGMFg

rest:
  userServiceLink: http://localhost:9097/api/v1/crud/users
  createAccountLink: http://localhost:9097/api/v1/crud/users/accounts
  accountServiceLink:  http://localhost:9097/api/v1/crud/accounts