server:
  port: 9098
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop


secret:
  token: t.AH0I6SMNFaFJhnATn36NMf7Rlv06sItlSlid1U45zRF4Uks0OargwwuMxNe_fBOvwptnmD5-4cFQgJKTfEVe1w